// Replays the golden vectors generated by scripts/generate-flow-vectors.ts
// against the C++ port and compares canonical serializations. A mismatch
// means the two implementations of the decision layer disagree — fix the C++
// side (the TS side is the reference) or regenerate stale vectors.
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

#include "../flow_json.h"
#include "../update_flow_core.h"

using flowjson::Parse;
using flowjson::Stringify;
using flowjson::Value;

namespace {

Value Dispatch(const std::string& fn, const Value& args, bool* known) {
  *known = true;
  if (fn == "murmurhash3_32_gc") {
    return Value::Number(updateflow::Murmur3_32(args.At(0).AsString()));
  }
  if (fn == "isInRollout") {
    return Value::Bool(
        updateflow::IsInRollout(args.At(0).AsNumber(), args.At(1).AsString()));
  }
  if (fn == "joinUrls") {
    return updateflow::JoinUrls(args.At(0), args.At(1));
  }
  if (fn == "orderEndpointCandidates") {
    return updateflow::OrderEndpointCandidates(args.At(0),
                                               args.At(1).AsNumber());
  }
  if (fn == "buildCheckRequestBody") {
    return updateflow::BuildCheckRequestBody(args.At(0));
  }
  if (fn == "resolveCheckResult") {
    return updateflow::ResolveCheckResult(args.At(0), args.At(1));
  }
  if (fn == "decideDownload") {
    return updateflow::DecideDownload(args.At(0), args.At(1),
                                      args.At(2).Truthy());
  }
  *known = false;
  return Value::Undefined();
}

// The parser consumes network data (checkUpdate responses); malformed and
// hostile inputs must set ok=false without crashing — this suite runs under
// ASan+UBSan in CI. Valid-but-tricky inputs pin the JS JSON.parse semantics
// the port relies on.
int RunParserRobustness() {
  int failures = 0;

  const char* malformed[] = {
      "",
      "{",
      "[1,2",
      "\"abc",
      "{\"a\":}",
      "{\"a\" 1}",
      "{\"a\":1,}",
      "[1,]",
      "tru",
      "nul",
      "falsy",
      "1x",
      "1 2",
      "- 1",
      "\"\\q\"",
      "\"\\u12\"",
      "\"\\ud800\\u0041\"",  // high surrogate followed by a non-low escape
      "{\"a\":1}garbage",
      "[}",
      "{]",
  };
  for (const char* input : malformed) {
    bool ok = true;
    Parse(input, &ok);
    if (ok) {
      std::fprintf(stderr, "robustness: accepted malformed input: %s\n", input);
      failures++;
    }
  }

  // Nesting: 64 levels parse, 65 are rejected (stack-depth cap).
  for (int depth : {64, 65}) {
    std::string nested;
    for (int i = 0; i < depth; i++) {
      nested.push_back('[');
    }
    for (int i = 0; i < depth; i++) {
      nested.push_back(']');
    }
    bool ok = false;
    Parse(nested, &ok);
    bool expected = depth <= 64;
    if (ok != expected) {
      std::fprintf(stderr, "robustness: depth %d parsed=%d, expected %d\n",
                   depth, ok, expected);
      failures++;
    }
  }
  // A deeply nested bomb must fail cleanly, not overflow the stack.
  {
    std::string bomb(100000, '[');
    bool ok = true;
    Parse(bomb, &ok);
    if (ok) {
      std::fprintf(stderr, "robustness: accepted nesting bomb\n");
      failures++;
    }
  }

  // Valid-but-tricky inputs: assert the parsed value via canonical stringify.
  const struct {
    const char* input;
    const char* expected;
  } tricky[] = {
      // Duplicate keys: first position, last value (JSON.parse semantics).
      {"{\"a\":1,\"b\":2,\"a\":3}", "{\"a\":3,\"b\":2}"},
      {"\"\\u00e9\"", "\"\xc3\xa9\""},                    // BMP escape -> UTF-8
      {"\"\\ud83d\\ude00\"", "\"\xf0\x9f\x98\x80\""},     // surrogate pair
      {"  {  \"a\" : [ 1 , true , null ] }  ", "{\"a\":[1,true,null]}"},
      {"-0.5", "-0.5"},
      {"1e2", "100"},
  };
  for (const auto& t : tricky) {
    bool ok = false;
    Value v = Parse(t.input, &ok);
    std::string actual = Stringify(v);
    if (!ok || actual != t.expected) {
      std::fprintf(stderr,
                   "robustness: %s -> ok=%d %s (expected %s)\n", t.input, ok,
                   actual.c_str(), t.expected);
      failures++;
    }
  }

  return failures;
}

}  // namespace

int main(int argc, char* argv[]) {
  if (argc < 2) {
    std::fprintf(stderr, "usage: %s <flow_vectors.json>\n", argv[0]);
    return 2;
  }
  std::ifstream file(argv[1]);
  if (!file) {
    std::fprintf(stderr, "cannot open %s\n", argv[1]);
    return 2;
  }
  std::stringstream buffer;
  buffer << file.rdbuf();

  bool ok = false;
  Value doc = Parse(buffer.str(), &ok);
  if (!ok) {
    std::fprintf(stderr, "failed to parse %s\n", argv[1]);
    return 2;
  }

  const Value& cases = doc.Get("cases");
  int failures = RunParserRobustness();
  for (size_t i = 0; i < cases.Size(); i++) {
    const Value& testCase = cases.At(i);
    const std::string& fn = testCase.Get("fn").AsString();
    bool known = false;
    Value actual = Dispatch(fn, testCase.Get("args"), &known);
    if (!known) {
      std::fprintf(stderr, "case %zu: unknown fn %s\n", i, fn.c_str());
      failures++;
      continue;
    }
    std::string actualStr = Stringify(actual);
    std::string expectedStr = Stringify(testCase.Get("expected"));
    if (actualStr != expectedStr) {
      std::fprintf(stderr,
                   "case %zu (%s) MISMATCH\n  args:     %s\n  expected: %s\n"
                   "  actual:   %s\n",
                   i, fn.c_str(), Stringify(testCase.Get("args")).c_str(),
                   expectedStr.c_str(), actualStr.c_str());
      failures++;
    }
  }

  if (failures) {
    std::fprintf(stderr, "%d failures (%zu vectors + parser robustness)\n",
                 failures, cases.Size());
    return 1;
  }
  std::printf("all %zu flow vectors + parser robustness passed\n",
              cases.Size());
  return 0;
}
